### ISSUE TITLE
When item id contains a leading/trailing space character

### ISSUE THREAD

**Issue by vincent-gros** [IDPF/epubcheck#332]
If a non-Content Document (css, jpeg...) item id contains one or more leading/trailing spaces, no error or warning is provided by EpubCheck.

But, for a Content Document (xhtml, svg) item id, this is another story, because this id is used by the associated itemref.

In this context, `idref="content1"` is not associated to `id=" content1 "`, for example. Though this is the same normalized value.

[Here an EPUB2 sample](https://drive.google.com/file/d/0BzBMXg7nStOIdkdUVWExVmZCd0E/edit?usp=sharing)

[Here an EPUB3 sample](https://drive.google.com/file/d/0BzBMXg7nStOIS1dGaTFCOWZlQUk/edit?usp=sharing)

**Comment by rdeltour** [comment]
So I had a new look at that issue (finally!).

My understanding of the spec is that leading and trailing spaces are allowed and must be discarded when checking for ID equality ; this is coming from the XML spec [3.3.3 Attribute-Value Normalization](http://www.w3.org/TR/2008/REC-xml-20081126/#AVNormalize).

@mattgarrish can you please confirm?

I tried to fix it wherever I could find a potential issue (I hope I didn't miss too many checks, but it seems the issue is not too frequent since this wasn't reported before...).

**Comment by mattgarrish** [comment]
Right, it's a nuisance using schematron to check attributes for this reason, as you have to remember to normalize space before checking for equality as someone could slip in leading/trailing spaces.

Unlike with elements, it's also pretty rare find random whitespace around attribute values, so not surprising it's never come up before.
