### ISSUE TITLE
Html viewport is missing height and/or width in non-fixed layout documents

### ISSUE THREAD

**Issue by josteinaj** [IDPF/epubcheck#419]
Fixed layout publications [require height and/or width to be specified](http://www.idpf.org/epub/fxl/#dimensions-xhtml) in the content documents meta viewport, which I assume is why an error is thrown 

This does not seem to be a requirement for publications that are not fixed layout publications. The tools we use currently generate and validate `<meta name="viewport" content="width=device-width" />`. Could the [HTM_047 ("Html viewport is missing height and/or width.")](https://github.com/IDPF/epubcheck/blob/master/src/main/java/com/adobe/epubcheck/messages/MessageDictionary.java#L152) validation throw a warning instead of an error if the content document is not a fixed layout document?

(I'm using 4.0.0-alpha9-SNAPSHOT)

**Comment by madevelopers** [comment]
I also created a fixed layout epub recently and one of the html files has the following viewport declaration `<meta name="viewport" content="width= ,height= ">`. This causes the book to shrink when loaded on Kobo for Android. The issue is not present on iBooks and Kobo for iOS. I know this is somewhat off-topic, but I think it would be helpful to have a Warning message for this case.
