### ISSUE TITLE
epubcheck: refuses to check files not named *.epub

### ISSUE THREAD

**Issue by ezhukov** [IDPF/epubcheck#490]
Reported for epubcheck Debian package, but valid also for latest upstream alfa release jar.
Please refer to Debian bug report for details and/or contact me.
https://bugs.debian.org/773366

**Comment by tofi86** [comment]
At first I thought that the EPUB spec requires the `.epub` file extension, but the I read the OCF 2.0.1 spec (for EPUB 2) which says:

> 3.4	Container media type identification 
> […]
> OCF Container files **SHOULD** use an extension “.epub” to identify to processing applications that they are OCF Containers.

That's not a MUST, so I think an EPUB file without extension should be valid.

And also the OCF 3.0.1 spec doesn't require the extension:

> [Appendix C. The application/epub+zip Media Type](http://www.idpf.org/epub/301/spec/epub-ocf.html#app-media-type)
> […]
> Additional information: 
> […]
> File extension(s):
> OCF files are **most often** identified with the extension .epub.

So I'm gonna flag this as a bug in the current EpubCheck implementation but would like to also hear @rdeltour's opinion here...

**Comment by tofi86** [comment]
Hey @mattgarrish – can you confirm my observation regarding this topic? If so, we need to remove the file extension tests from EpubCheck

/ cc @rdeltour

**Comment by mattgarrish** [comment]
Sounds right to me. File extensions are only ever "should" where they're specified since they're not reliable.

The mimetype is the formal identifier that the zip contains an epub.

**Comment by tofi86** [comment]
Okay. So what do you suggest? Remove file extension tests completly? Make it a WARNING? Or rather INFO?

**Comment by mattgarrish** [comment]
Leave as a warning for EPUB 2, since it's a "should" there.

The requirement was clearly excised on purpose from 3.0, since the section and prose about the mimetype remain. I wasn't able to find an issue or any meeting notes, unfortunately. As the other file extension warnings were persisted, I'd guess maybe it was dropped here to accommodate vendors who might want to put their own extensions on files or possibly allow for profiles built on epub.

I don't know of the existence of such, and since there's been no big uproar about this over the years maybe just leave it as an INFO message that the extension is typically used.

If we adhere to the principle of not issuing error/warnings for things not in the spec, then there's no cause for anything higher than an info message.

**Comment by danielweck** [comment]
Note that in Readium the `*.epub3` file extension is supported in addition to `*.epub` (in order to detect the content type wherever `application/epub+zip` is not available). This is because there are OPDS feeds that reference such publication filenames.

**Comment by tofi86** [comment]
Okay, conclusion is:

* Make file extension tests a `WARNING` for EPUB 2 and a `INFO` for EPUB 3.0

Tasks are:

* Make file extension tests a `WARNING` for EPUB 2 and a `INFO` for EPUB 3.0
* Change the API and CLI interface so that files without extension are accepted by EpubCheck

Adding the label "reviewed & ready for implementation" so that someone can go and implement this.
