### ISSUE TITLE
Handling of foreign resources with fallbacks 

### ISSUE THREAD

**Issue by bitsgalore** [IDPF/epubcheck#511]
(Sorry for this issue description being a bit longish; originally wanted to post this to StackExchange as question on how to implement fallbacks, and then realised reporting this here is probably more appropriate/effective.) 

I'm trying to design an automated procedure for detecting EPUBs that contain [foreign resources](http://www.idpf.org/epub/301/spec/epub-publications.html#gloss-publication-resource-foreign) using Epubcheck. So I made a few test files. These are all variations of [this simple test document](https://github.com/bitsgalore/epubPolicyTests/blob/master/build/epub20_minimal.epub?raw=true) (which is well-formed EPUB 2.0 according to Epubcheck 3.0.1). You can browse its internal structure [here](https://github.com/bitsgalore/epubPolicyTests/tree/master/content/epub20_minimal).

## Test 1: foreign resource, no fallback

As a first step I replaced the .png image in that file by a .jp2 (JPEG 2000), and updated the references in the manifest ([link here](https://github.com/bitsgalore/epubPolicyTests/blob/master/content/epub20_foreign_resource_no_fallback/OEBPS/content.opf)) and the text ([link here](https://github.com/bitsgalore/epubPolicyTests/blob/master/content/epub20_foreign_resource_no_fallback/OEBPS/Text/pdfMigration.html)) Epubcheck then correctly establishes that the file is "Not well-formed" (output file [here](https://github.com/bitsgalore/epubPolicyTests/blob/master/epubcheckout/3.0.1/epub20_foreign_resource_no_fallback.xml)).

## Test 2: foreign resource with fallback

Next I wanted to test the behavior in case a fallback mechanism is present. The problem here is that I couldn't find any clear examples of how to implement this. I did find an example in the EPUB 2.0.1 spec that shows how to define a fallback in the manifest: 

<http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#TOC2.3.1.1>

Based on that I added a PNG image to my test file, and defined it as a fallback in the manifest:

    <manifest>
        <item href="toc.ncx" id="ncx" media-type="application/x-dtbncx+xml" />
        <item href="Text/pdfMigration.html" id="pdfMigration.html" media-type="application/xhtml+xml" />
        <item href="Images/pdfVenn.jp2" id="pdfVennJP2" media-type="image/jp2" fallback="pdfVennPNG" />
        <item href="Images/pdfVenn.png" id="pdfVennPNG" media-type="image/png" />
        <item href="Images/corruptedjp2_kdu_zoom3.jpg" id="corruptedjp2_kdu_zoom3.jpg" media-type="image/jpeg" />
        <item href="Text/cover.xhtml" id="cover.xhtml" media-type="application/xhtml+xml" />
    </manifest>
    
So the fallback is defined by its ID. However, in the text the image is referenced by its path location, without any explicit reference to its ID:

    <img alt="PDF Venn diagram" src="../Images/pdfVenn.jp2" />
 
This made me wonder how to refer to the image in the text. I tried two different approaches:

1. Leave the reference as-is. File [here](https://github.com/bitsgalore/epubPolicyTests/blob/master/build/epub20_foreign_resource_with_fallback_noID.epub?raw=true); source [here](https://github.com/bitsgalore/epubPolicyTests/tree/master/content/epub20_foreign_resource_with_fallback_noID)

2. Add the identifier to the image element as `<img alt="PDF Venn diagram" src="../Images/pdfVenn.jp2" id="pdfVennJP2" />`. File [here](https://github.com/bitsgalore/epubPolicyTests/blob/master/build/epub20_foreign_resource_with_fallback.epub?raw=true); source [here(https://github.com/bitsgalore/epubPolicyTests/tree/master/content/epub20_foreign_resource_with_fallback)]

Both files are well-formed according to Epubcheck (see the output files [here](https://github.com/bitsgalore/epubPolicyTests/tree/master/epubcheckout/3.0.1)); however neither Calibre nor Readium (Chrome app) show the image that uses the fallback. This makes me wonder whether  Epubcheck's validation is accurate/complete on this? 

(BTW if anyone could point me to an example of how to implement this correctly that would be really useful as well.)

**Comment by mattgarrish** [comment]
You don't do anything special in the content for manifest fallbacks. The reading system is expected to handle swapping the unsupported media type for the supported one. The only requirement is that the fallback attribute reference the fallback manifest item, so epubcheck is doing all it can.

The problem is that not all reading systems support all the features of epub, and manifest fallbacks are still poorly supported, as you're finding.

If you go to epubtest.org, click on the "compare features" link and then find the Manifest section you can tick off the tests to get a report. I think I spotted only three positives.

**Comment by bitsgalore** [comment]
Hi Matt,

Thanks for the explanation, this makes sense. Surprised to see the lack of support of this feature though, seeing that it dates back to EPUB 2. I'll close this issue now as this is obviously not an epubcheck bug. Thanks again!

**Comment by mattgarrish** [comment]
There are a few spec features that have never gained a lot of traction, and are known irritants for content producers. Fallbacks are one, and you’re going to find a similar lack of support if you look to epub:switch as an alternative.

Some of these epub-specific features have found their way into deprecation (oeb-page-head/oeb-page-foot), and others are on the bubble for the next revision (switch, triggers and bindings).

I can’t tell you why developers don’t support what they don’t support, but given finite resources for development there’s always prioritization, and handling content that isn’t required in the spec doesn’t get a lot of attention. Checking epubtest.org for real-world support is always useful in addition to the strict spec-conformance validation that epubcheck provides.

Matt

**Comment by jstallent** [comment]
Matt,

Can you tell me what is on deck to replace epub:switch? For content producers, there needs to be a viable method for defining fallbacks for other content that is not supported across devices, such as MathML and SVG. While switch is not supported on many devices yet, I think it offers a great potential solution for cross-platform compatibility, and is something that is not hard for content creators to add in. I'm interested to know what will replace it.

Thanks!
Joshua

**Comment by mattgarrish** [comment]
At this point there hasn’t been any talk of replacements, as 3.1 still hasn’t been chartered yet. I wouldn’t expect anything new to be built on top of html, though.

And, to be clear, that a desire to deprecate the epub extensions was raised during the discussion of changes for 3.1 at the Phoenix edupub meetings doesn’t mean that will happen in 3.1. It’s just likely those elements will be on the table, given there was positive reception for the idea. (And, of course, they’ll live on for the life of epub 3 even if they are deprecated.)

The switch element was a particular focus, because the lack of support for it has meant many in the audience were simply avoiding it entirely because content often either wouldn’t show up, or was showing up in duplicate, depending on support. As the OP noted, it’s been around so long without good support, and people are reaching a frustration point with it.

I think it was Markus who sent out an email to the working group list yesterday or the day before that IDPF is planning to hold a series of meetings to discuss the 3.1 revision around the beginning of April, so there’s still plenty of opportunity to voice your opinion before the revision even begins.

Matt
