### ISSUE TITLE
non-standard image resource

### ISSUE THREAD

**Issue by amdobritt** [IDPF/epubcheck#519]
Results: The following problems were found in Ebook Sample Short Fiction by Anna Dobritt.epub:

Type	File	Line	Position	Message
ERROR	OPS/body17.xhtml	6	94	non-standard image resource 'OPS/images/Anna-Dobritt.jpg' of type 'image/jpg'
ERROR	OPS/body2.xhtml	17	91	non-standard image resource 'OPS/images/bookplateA.jpg' of type 'image/jpg'
ERROR	OPS/body15.xhtml	6	93	non-standard image resource 'OPS/images/ravenflightA.jpg' of type 'image/jpg'
ERROR	OPS/body12.xhtml	14	89	non-standard image resource 'OPS/images/rwcvoneA.jpg' of type 'image/jpg'

Why do I keep getting this error?

**Comment by mattgarrish** [comment]
You’re getting those errors because you have “image/jpg” in the media-type attributes for your images (in the manifest).

The registered media type for JPEGs is image/jpeg.[1] Add the ‘e’ to fix.

[1] http://www.iana.org/assignments/media-types/media-types.xhtml#image

Matt

From: amdobritt 
Sent: Sunday, March 22, 2015 10:09 AM
To: IDPF/epubcheck 
Subject: [epubcheck] non-standard image resource (#519)

Results: The following problems were found in Ebook Sample Short Fiction by Anna Dobritt.epub:

Type File Line Position Message
ERROR OPS/body17.xhtml 6 94 non-standard image resource 'OPS/images/Anna-Dobritt.jpg' of type 'image/jpg'
ERROR OPS/body2.xhtml 17 91 non-standard image resource 'OPS/images/bookplateA.jpg' of type 'image/jpg'
ERROR OPS/body15.xhtml 6 93 non-standard image resource 'OPS/images/ravenflightA.jpg' of type 'image/jpg'
ERROR OPS/body12.xhtml 14 89 non-standard image resource 'OPS/images/rwcvoneA.jpg' of type 'image/jpg'

Why do I keep getting this error?
