### ISSUE TITLE
epubcheck v.4.0.0-alpha11: Corrupted image file encountered

### ISSUE THREAD

**Issue by Matt-1** [IDPF/epubcheck#567]
I have an EPUB with an image that is reported to be corrupted:
`ERROR(PKG-021): image.epub/OEBPS/images/image1.jpg(-1,-1): Corrupted image file encountered.`
However, the image seems to be fine. Neither Gimp, IrfanView or ImageMagick's identify report any errors. identify outputs:
`image1.jpg JPEG 482x379 482x379+0+0 8-bit DirectClass 1.872MB 0.020u 0:00.030`

An example EPUB can be found here: http://devel.springer.de/image.epub.

**Comment by rdeltour** [comment]
I could repro with the provided sample. Not sure where this is coming from, but I'll have a deeper look, thanks for the report!

**Comment by jstallent** [comment]
FYI, this only happens in EPC4, not in EPC3.

**Comment by william-r-greene** [comment]
Romain, I just got your Sept. 1 posting to download EpubCheck 4.0.0 from https://github.com/IDPF/epubcheck/releases/tag/v4.0.0, which I did.  That version also yields the "Corrupted image file" error for a valid JPEG file:

   ERROR(PKG-021): ./generated/ibooks/mchs.epub/iTunesArtwork(-1,-1): Corrupted image file encountered.

I am attaching the allegedly corrupt image file.  I had to rename it from ITunesArtwork to iTunesArtwork.jpg in order to upload it.

![itunesartwork](https://cloud.githubusercontent.com/assets/3003572/9700529/1c998682-53d4-11e5-93e3-2a4f2dd64763.jpg)

**Comment by rdeltour** [comment]
thank you for the sample :+1:  I'll have a deeper look ASAP.

**Comment by rdeltour** [comment]
I wasn't able to reproduce when integrating the uploaded image in a test EPUB.
Are you sure you used version 4.0.0? with which Java version?
Could you upload a full EPUB sample?

**Comment by tofi86** [comment]
> ERROR(PKG-021): ./generated/ibooks/mchs.epub/iTunesArtwork(-1,-1): Corrupted image file encountered.
> 
> I am attaching the allegedly corrupt image file. I had to rename it from ITunesArtwork to iTunesArtwork.jpg in order to upload it.

isn't the JPG file extension mandatory?
