### ISSUE TITLE
ePub file containing ID attribute beginning with number passes validation

### ISSUE THREAD

**Issue by LeoRC** [IDPF/epubcheck#706]
I have an ePub document which contains an id attribute with a value which starts with a number. It seems that Kobo's (ref @bdugas ) ePub validation software treats this as an error, which is apparently correct as it's invalid XML. However epubcheck 4.0.1 (I used Pagina as well as http://validator.idpf.org/ ) appears to validate the document ("No errors or warnings detected. EPUB is valid!") as an EPUB 3.0.1 document. This seems to be more or less the reverse of issue #193 .

Here is a sample ePub replicating the problem: it passes validation despite containing the same id attribute beginning with a number (in the file front_matter.xhtml ).  [democrop1.zip](https://github.com/IDPF/epubcheck/files/464010/democrop1.zip)

Apparently the error generated by Kobo's software was this:

> \nvalidationType: null\n resource: OPS/front_matter.xhtml\n line: 124\n column: 56\ndescription: value of attribute \&quot;id\&quot; is invalid; must be an XML name without colons\nvalidationType:

. I don't have much more detail as all I was given was a long error message cut and pasted into a Word document without context. All I can add is that this is not the only apparent discrepancy between epubcheck 4.0.1 and whatever Kobo is using.

**Comment by rdeltour** [comment]
IDs in HTML can perfectly start with digits, see the definition in the [HTML5 spec](https://www.w3.org/TR/html5/dom.html#the-id-attribute) referenced from EPUB.

See also #355 .

Closing as invalid, feel free to comment or reopen if you disagree.

**Comment by LeoRC** [comment]
Does that also apply to HTML5-as-XHTML documents, though, like ePub .xhtml files? It seems odd that the standard for a particular XML namespace or set of namespaces could override the fundamental validity rules for XML itself. Obviously ordinary HTML5-as-vendor-soup documents aren't constrained to be XML and so are in a different position.

**Comment by mattgarrish** [comment]
It's not being applied XML's ID type, so the rules for ID validity don't apply. It's just a CDATA string minus spaces. That's how they're choosing to define the attribute, so it's valid to their definition.

It's not compatible with EPUB 2, so going crazy with HTML5 looseness is a question you need to weigh for yourself. I can see reasons why vendors would want the ids to remain compatible, so they can translate an incoming EPUB without having to monkey with the data. Since XML IDs are not incompatible with the HTML5 definition, it's acceptable for a vendor to impose the strong requirement on content they ingest.

**Comment by LeoRC** [comment]
I'm certainly going to change the ID attribute name as there's no major reason not to. However it's good to know that the original form was in fact valid.
