### ISSUE TITLE
Add a --version switch

### ISSUE THREAD

**Issue by tofi86** [IDPF/epubcheck#743]
The `epubcheck.jar` should have a `--version` switch to display the version information only.

**Comment by tofi86** [comment]
hey @rdeltour, we already parse the argument string for a `--version` string in https://github.com/IDPF/epubcheck/blob/master/src/main/java/com/adobe/epubcheck/tool/EpubChecker.java#L541

Seems this was introduced as an alternative to the `-v` switch when using in conjunction with `--mode` / `-m`.

However, it's not documented anywhere. Not in commandline help `--help` nor in the wiki: https://github.com/IDPF/epubcheck/wiki/Running

What do you think, shall we just drop support for alternates `-version` and `--version` and make `--version` print the EpubCheck version number?

**Comment by tofi86** [comment]
Postponed to a later version, as this is causing conflicts with the current commandline arguments

**Comment by kamorrissey** [comment]
I'd like to get my feet wet as a contributor, and this seemed like a modest item. If I understand correctly, the "ready for implementation" tag makes it suitable to work on. Is this right?

**Comment by tofi86** [comment]
Glad to see new volunteers, @kamorrissey! Welcome!

If we can agree on having two different meanings for the `--version` switch, this issue is ready to go!
I can live with it tbh.

**Comment by rdeltour** [comment]
> Glad to see new volunteers, @kamorrissey! Welcome!

+1, hi and welcome @kamorrissey 👋

> If we can agree on having two different meanings for the --version switch, this issue is ready to go!
> I can live with it tbh.

It seems the current `--version` (or `-v`) option is used to declare the EPUB spec version against which to check when validating single documents (with the `--mode` option), since in that case we can’t get the EPUB version from the OPF.

I agree that it can be pretty confusing with `--version` typically being used in a CLI to display the tool’s version.

We’d have a couple options:
1. remove `--version` from its previous usage, and use it to display the tool’s version
2. rename the `-v`|`--version` option to something else (e.g. `-s`|`--spec-version`, or `-t`|`--target-version`)
3. keep the current use of the `--version` option, and make it display the tool’s version number only when the mode `--mode` is *not* specified

I don’t have a strong opinion; I don’t know if this option is heavily used out there. Option 3 is the less disruptive, but the most confusing.

**Comment by kamorrissey** [comment]
I've been considering it. I'm in favor of option 1, since the --help message does not mention --version. I already have a proposed implementation that I'm going to submit in a pull request.

**Comment by rdeltour** [comment]
> I've been considering it. I'm in favor of option 1

Sounds good to me!

**Comment by kamorrissey** [comment]
Created a pull request for review.

**Comment by tofi86** [comment]
PR #841

Awesome, thanks @kamorrissey 👏 

We'll try to have a look asap!
