### ISSUE TITLE
The Embeding "EPUB Check Logo" into XHTML

### ISSUE THREAD

**Issue by teytag** [IDPF/epubcheck#760]
![img_0245](https://cloud.githubusercontent.com/assets/6927098/26726683/afbbe414-47ac-11e7-8595-dda9678cb6c0.jpg)

Hi @tofi86
I will be suggestion for EPUB check new features. -> https://github.com/IDPF/epubcheck/wiki/WorkPlan#new-features
If it's validated after EPUB check proccess **"EPUB Check Logo"** can embed into _"toc.xhtml"_ file. So that the each epubs will be reliable and readers can be check to this epub with specific QR code. 

### **Example use case:**
**App:** EPUB Check application.
**Logo:** EPUB Check Logo (like a at example picture)
1. EPUB3 folder drag into app.
2. That's all OK. No errors or warnings.
3. App creates dynamic QR code and logo.
3. App embeds the logo into "toc.xhtml" file.
4. And ".epub" is ready.

### **Objective**
1. To certify EPUB files according to the standards.
2. Encourage the use of EPUB Check.
3. Encourage designers to make EPUB output conforming to the standards (metadata should be the designer's name in the information)
4. Online verification with log QR code and get metadata information.
5. Other logs

**Comment by tofi86** [comment]
Hi @teytag,

thanks for your feature proposal and the clarification, but I think this is **out of scope of the EpubCheck project.**

EpubCheck does not provide any mechanism to alter or update the validated EPUB file, and IMHO it also should never do that as it could cause unexpected side effects in the otherwise correct EPUB file.
This could be done by a third party App or an Editor, but not with EpubCheck.

From what I know of EPUB distribution, in Germany you cannot publish an EPUB file commercially in one of the big shops without passing EpubCheck. So *every* EPUB would have this logo attached.
Also I think, the customers don't care or just don't know what EpubCheck is.

Adding the logo to the ZIP, toc.xhtml and OPF, generating a QR code from whatever URL and re-packaging the ZIP seems to be too much development effort for what you want to achieve.

I'm going to close the issue, mainly because EpubCheck will never ever alter the EPUB file. Sorry.

Cheers,
Tobias
