### ISSUE TITLE
Unjustified error regarding framespacing

### ISSUE THREAD

**Issue by Matt-1** [IDPF/epubcheck#803]
I have an EPUB3 file that contains
`<mtable class="matrix" columnalign="center" framespacing="0em">`

epubcheck 4.0.2 reports the following error:
> Validating using EPUB version 3.0.1 rules.
> ERROR(RSC-005): framespacing.epub/EPUB/xhtml/epub30-overview.xhtml(15,70): Error while parsing file 'value of attribute "framespacing" is invalid; missing token; must be a string matching the regular expression "\s\*((-?[0-9]\*([0-9]\.?|\.[0-9])[0-9]*(e[mx]|in|cm|mm|p[xtc]|%)?)|(negative)?((very){0,2}thi(n|ck)|medium)mathspace)\s\*"'.

However, the value "0em" seems to match the regular expression, so it's not clear to me what the problem is. Could you please check?

The EPUB file can be found here: http://devel.springer.de/framespacing.epub

**Comment by tofi86** [comment]
Okay, this is tricky. The displayed regex is indeed NOT matching your `0em` value, because of the dots inhere: `([0-9].?|.[0-9])` They would need to be escaped, otherwise they also match characters, etc.: `([0-9]\.?|\.[0-9])`. So from a first sight, indeed only `0e` is matching, not the whole `0em`.

However, when looking into the sources the regex is defined correctly:

https://github.com/IDPF/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/mod/mathml/mathml3-common.rnc#L82

So from my point of view, your code seems correct and there shouldn't be a validation error.

However, even @oxygenxml v19.1 throws an error for your particular HTML document, so this may be a bug with Jing? @raducoravu do you probably have an idea?

**Comment by murata0204** [comment]
I validated 

```
<foo>
    <bar>0em</bar>
    <baz>0em</baz></foo>

```


against 

```
datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

start  = element foo { element bar { bardt } , element baz  { bazdt } }


bardt = xsd:string {
  pattern = '\s*((-?[0-9]*([0-9].?|.[0-9])[0-9]*(e[mx]|in|cm|mm|p[xtc]|%)?)|(negative)?((very){0,2}thi(n|ck)|medium)mathspace)\s*' 
}

bazdt = xsd:string {
  pattern = '\s*((-?[0-9]*([0-9]\.?|\.[0-9])[0-9]*(e[mx]|in|cm|mm|p[xtc]|%)?)|(negative)?((very){0,2}thi(n|ck)|medium)mathspace)\s*' 
}

```

using oXygen and got no validation errors.

**Comment by mattgarrish** [comment]
Isn't the error here related to this:  "missing token".

framespacing requires both an h-unit and v-unit, so framespacing="0em" is invalid as one or the other is missing.

**Comment by mattgarrish** [comment]
I just tested framespacing="0em 0em" and the error correctly disappears. The message isn't the clearest, but I don't see that anything is wrong with the validation.

**Comment by tofi86** [comment]
Oh, sorry, I was totally focused on the regex and didn't pay attention to how the `framespacing` attribute is defined:

```
 attribute framespacing {list {length, length}}?,
```

Indeed, the message isn't the clearest, but I don't see how to improve it as it comes from Jing.

Closing as invalid.

**Comment by Matt-1** [comment]
Thank you everyone and my apologies for the incorrect title. Based on the error message, I though there was a problem with "0em" not matching the regex, but now it's clear that that wasn't the actual error.
