### ISSUE TITLE
[Question] Test clean up

### ISSUE THREAD

**Issue by kalaspuffar** [IDPF/epubcheck#824]
Hi @rdeltour @tofi86 @mattgarrish 

I've just read through the Clean up Test documentation on the wiki with all the different links. And I just want to clarify that I understood the task.

We need to reorganize the test under src/test/resources and all these are present in multiple directories today namely
20
30
com.adobe.epubcheck
css
minimal-epub
stress

All of these are incorrect and need to be replaced with new tests.

The new test directory should be called src/test/resources/testFiles ? (don't like the camelcase where a package name is more java native eg. "test.files". I'm not really keen on the naming either but if you decided then I will fall in line.

The rest of the structure under testFiles should follow the outlined structure from the epubcheck Tests Directory Structure Proposal with either long names or short names depending on the first implementer doing the job.

Last part that puzzled me was that the proposal talked about using exploded epubs preferably for readability or reusability of tests. I'm not sure what the benefits are but I might have missed something there.

The reason I ask these questions is that I might get bored during the holidays and if I don't have any private projects that need tinkering I might give this task a go.

Best regards
Daniel

**Comment by tofi86** [comment]
Hej Daniel,

the tests in `20` and `30` are quite okay compared to the ones in `com.adobe.epubcheck` so I would assign them with lower priority.

The tests in `com.adobe.epubcheck` are high priority because most code changes result in huge JSON/XML/RDF report diffs because of the "dirty" test epubs and this is the biggest pain point in maintaining the current tests.

`minimal-epub` is not a testcase but an epub template which could/should be used for new tests and which shouldn't generate any side-effect error/warning/usage messages (did a cleanup recently).

I don't have any preference on how to name the test directory. @rdeltour ?

The point about using exploded EPUBs is mainly that changes in the test files inside an EPUB can be diffed with Git whereas diffing changes in a packaged `*.epub` file is not possible.

I hope this helps! Feel free to ask further questions if necessary, I'll keep an eye on this post ;-)

God jul! 🎄 🎅

**Comment by tofi86** [comment]
Hi Daniel, are you okay if we close this issue? Or shall we keep it open for another while?

Do we need to improve the wiki docs?

**Comment by kalaspuffar** [comment]
I think we can close this issue but updating the wiki docs so the task is clear would be good due to the fact that we are working part-time on these issues and sadly might forget discussions.

**Comment by tofi86** [comment]
I linked to this issue from the wiki page.
