### ISSUE TITLE
not a valid URI

### ISSUE THREAD

**Issue by dalmear** [IDPF/epubcheck#837]
I am getting this error:
ERROR(RSC-020): *****.epub/OEBPS/Text/chapter12.xhtml: www.glorecords.blm.gov/reference/default.aspx#id=05_Appendices&#124;01_Glossary is not a valid URI.

I can't send the actual file because it is owned by the client and protected by a copyright, but here is the part where the code is used

**Comment by dalmear** [comment]
Please reply asap

**Comment by amandasramalho** [comment]
Hi @dalmear. Try to insert "http://". Sometimes it gives error because of it.
http://www.glorecords.blm.gov/reference/default.aspx#id=05_Appendices&#124;01_Glossary

**Comment by rdeltour** [comment]
@dalmear yeah, it’s probably what @amandasramalho said (👍 ).

I had seen the issue this morning, but to be honest I didn’t bother answering it right away. EpubCheck is open source and maintained by volunteers, so a comment saying "please reply asap" is frankly off-putting and counter-productive, especially without any kind of introduction.

Also, note that this issue tracker is not a user support forum. If you believe that the error messages you get shouldn't happen, if you believe they are caused by a bug, then please describe why –and what behavior you would expect instead– in the issue description.

Thank you.

**Comment by dalmear** [comment]
@amandasramalho thank u, will check and reply

**Comment by dalmear** [comment]
@rdeltour oops sorry
